version: '3.9'

services:

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: vpn_bot_api
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///data/vpn_bot.db
    depends_on:
      {}
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --proxy-headers

  bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: vpn_bot_worker
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///data/vpn_bot.db
    depends_on:
      {}
    command: python -m bot.main

volumes: {}

